### ISSUE TITLE
Hive warehouse replicaton and hive batch metastore replication

### ISSUE THREAD

**Issue by avdheshkrgarg** [airbnb/reair#24]
Hi,
If I want to send hive/warehouse replication from one cluster to another cluster its not successfull.
can you send me some parameter are requried for changes and which user to run.how to use blacklist parameter with database and tables.

and one of batch.metastore.replication which configuration file is edit. 
one is mysql and  second one is without mysql.

**Comment by plypaul** [comment]
Sorry, could you be a little more specific in your request?

**Comment by plypaul** [comment]
Looks like this one was from a long time ago, so I will go ahead and close this one. Please re-open as necessary.
