### ISSUE TITLE
nameserver support

### ISSUE THREAD

**Issue by hn5092** [airbnb/reair#37]
this version reair dont support two namesever , should add man config exp:
<property>
        <name>dfs.nameservices</name>
        <value>srcCluster,destCluster</value>
    </property>
    <property>
        <name>dfs.ha.namenodes.srcCluster</name>
        <value>nn1,nn2</value>
    </property>
    <property>
        <name>dfs.ha.namenodes.destCluster</name>
        <value>namenode317,namenode319</value>
    </property>
    <property>
        <name>dfs.namenode.rpc-address.srcCluster.nn1</name>
        <value>a1-ops-hdnamenode01.hz:8020</value>
    </property>
    <property>
        <name>dfs.namenode.rpc-address.srcCluster.nn2</name>
        <value>a1-ops-hdnamenode02.hz:8020</value>
    </property>
    <property>
        <name>dfs.namenode.rpc-address.destCluster.namenode317</name>
        <value>a2-prod-sh-namenode-XX-124.sh:8020</value>
    </property>
    <property>
        <name>dfs.namenode.rpc-address.destCluster.namenode319</name>
        <value>a2-prod-sh-namenode-XX-123.sh:8020</value>
    </property>
    <property>
        <name>dfs.client.failover.proxy.provider.srcCluster</name>
        <value>org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider</value>
    </property>
    <property>
        <name>dfs.client.failover.proxy.provider.destCluster</name>
        <value>org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider</value>
    </property>

**Comment by plypaul** [comment]
@hn5092 That configuration fits better in `hdfs-site.xml` instead of the reair configuration file.
