### ISSUE TITLE
file checksum with different blocksize maybe Invalid

### ISSUE THREAD

**Issue by hn5092** [airbnb/reair#51]
with different cluster  if they blocksize is different, in the stage 3 , it will be fail, because directoryCopier.equalDirs  must return false ,they checksum are different, if file size bigger than one block size ,it must be happen. now i check file use they bytes. 
below is they different checksum 
/test/123.lzo	MD5-of-0MD5-of-512CRC32C	
/test/123.lzo	MD5-of-0MD5-of-256CRC32C

**Comment by plypaul** [comment]
@hn5092 - this has likely been resolved with https://github.com/airbnb/reair/pull/55 - please re-open if this is not the case.
