### ISSUE TITLE
Have you ever tried Spark integration?

### ISSUE THREAD

**Issue by sungjuly** [airbnb/reair#62]
Thanks for open sourcing this project, I'm having an issue to integrate Spark app to record audit logs using `hive-hooks` module. Just curious have you ever tried Spark integration? It seems the Spark supports Hive hooks theoretically, but it doesn't work when initializing remote HiveMetastore client.

**Comment by sungjuly** [comment]
To be more clearly, in order to track/audit all transactions for incremental update, I also should consider Spark use cases. Ideally the `HiveContext` of Spark supports Hive Hooks natively but unfortunately, there's bugs or intentional ignoring Hive Hooks in the Spark (https://issues.apache.org/jira/browse/SPARK-18879) Thus, I was trying to test two ways more in the Spark.

* Leveraging Spark thrift server
Officially the Spark supports HiveServer2's thrift spec to integrate 3rd party services such as Tableau, ChartIO - http://spark.apache.org/docs/2.0.2/sql-programming-guide.html#running-the-thrift-jdbcodbc-server. I expected that Spark thrift server supports Hive Hooks as HiveServer2. Yes, that's half true. The Hive Hooks worked under 1.6.3 of Spark. Over 2.0.0 versions of Spark doesn't support Hive Hooks anymore. They feel like Hive Hooks is not included in Spark feature. - https://issues.apache.org/jira/browse/SPARK-19457

* Using HiveServer2 from Spark as JdbcRDD
This way cannot leverage Spark processing, it means Spark just use query results from HiveServer2. The processing performance will be very poor because it's same as Hive

I'm wondering how do you capture audit logs from Spark at Airbnb?

**Comment by plypaul** [comment]
@sungjuly - sorry for the delay, but what we've ended up doing at Airbnb is to implement audit logging using a listener in the Hive metastore Thrift server. This way, changes get picked up regardless of whether you use Hive or Spark. The documentation is not in yet, but the code to do this has been merged into the project. See:

https://github.com/airbnb/reair/blob/61d433de146c4e9f04fa324bb3b8794c0ad42911/hive-hooks/src/main/java/com/airbnb/reair/hive/hooks/MetastoreAuditLogListener.java

**Comment by plypaul** [comment]
Let us know if you would like to try that out, and we can update the README with more details.

**Comment by sungjuly** [comment]
@plypaul Nice! It would be great if you could update README file.

**Comment by sungjuly** [comment]
@plypaul It worked if using `MetastoreAuditLogListener` instead of `HiveHooks`, thanks!

**Comment by plypaul** [comment]
@sungjuly Glad to hear! Just pushed the branch README update, but here it is: https://github.com/airbnb/reair/pull/63
