### ISSUE TITLE
cp:  ...    No such file or directory

### ISSUE THREAD

**Issue by mzjgithub** [airbnb/reair#9]
private static void copyFile(Path srcFile, Path destFile) throws IOException {
        String[] copyArgs = { "-cp", srcFile.toString(), destFile.toString() };

        FsShell shell = new FsShell();

//1.============Whether it should be like this：======================
 String[] copyArgs = { "-put", srcFile.toString(), destFile.toString() };      

//2.================================================
I ask, whether the project is still in development

**Comment by plypaul** [comment]
1. We're using `cp` as it should be copying between HDFS filesystems instead of from local to remote.
2. The system is in production, but we are adding features.

**Comment by plypaul** [comment]
Can you put the full stack trace of the error that you're getting?

**Comment by plypaul** [comment]
Tagging @mzjgithub in case you didn't see the above messages.

**Comment by mzjgithub** [comment]
@plypaul     I might use is a problem, I try

**Comment by plypaul** [comment]
Okay, I'm going to close this issue for now, please re-open if necessary.
